WQP-1624 -- Update to use uuid for request identifier
NWQMC/WQP-WQX-Services pull request #353
Opened 2021-03-17 13:13 UTC by orosz-usgs

Before making a pull request
----------------------------

- [ ] Make sure all tests run
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
If no JIRA ticket is referenced, describe the changes made. Note anything that you want the reviewers to know while
reviewing your pull request

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the JIRA ticket
- [ ] Assign someone to review unless the change is trivial

2021-03-17 21:12 UTC, ee-usgs commented on src/main/java/gov/usgs/wma/wqp/dao/LogDao.java
>  			String id = field == null || field.isNull() ? null : field.asText();
I don't think these two lines are needed:  Just keep your UUID and reuse its value on line 109 for 'id'.
Also, on line 108, its really hard to read the logic there w/o parenthesis.  I find it more readable like this:
`String stage = (field == null || field.isNull()) ? null : field.asText();`

2021-03-17 21:14 UTC, ee-usgs approved these changes
I marked one small change.  I'm not sure why we need a UUID, since the entire request is on one 'row' now.

2021-03-17 21:27 UTC, ee-usgs requested changes
Also, after a chat with Jim, it sounds like we can just remove the recordCount (and its AtomicInteger counter) completely.  Since its not unique, it is only misleading and someone hunting the logs would be better off using the timestamps

2021-03-18 18:06 UTC, orosz-usgs commented
The id is passed up to the Log Service, up to the Controller by the
Log service.  Neither the log Service or the controllers were changed.
I think we should continue to return an unique id for each request,
as before. Do not know what assumptions the code is making.

2021-03-18 18:19 UTC, merged