WQP-1703 -- Corrected url path in GeoJson "siteUrl" field.
NWQMC/WQP-WQX-Services pull request #389
Opened 2021-09-13 23:31 UTC by orosz-usgs

*) new siteBaseUrl property in ConfigurationService
   *) Update controller to pass in provider url
   *) Updated transformer to use the passed in url rather
than build a path with a hard coded "provider" string
   *) updated tests
   *) Updated timeout test to use a non-routable IP address
   *) Updated dependencies

Before making a pull request
----------------------------

- [ ] Make sure all tests run
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
If no JIRA ticket is referenced, describe the changes made. Note anything that you want the reviewers to know while
reviewing your pull request

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the JIRA ticket
- [ ] Assign someone to review unless the change is trivial

2021-09-15 21:39 UTC, ee-usgs requested changes
I see a few places where I think small tweaks can make the code better for our future selves.  Nice work though - I can see this was more that just replacing some text.

2021-09-15 21:39 UTC, ee-usgs commented on src/main/java/gov/usgs/wma/wqp/service/ConfigurationService.java
>  	}
The name of the resulting methods is confusing.  Perhaps:
* getHostURL()
* getContextURL()
Also some javadocs to say what we are getting.  Does it include "http://"?  Does it end w/ a slash?

2021-09-15 21:39 UTC, ee-usgs commented on src/main/java/gov/usgs/wma/wqp/transform/BaseMapToJsonTransformer.java
> +
Javadocs of this would be nice, at least for the aspects of it you understand at this moment.  When some params are left out of a constructor, I think its good to mention why or what happens to them.
```
Constructor for instances that provide site url data from the db.
siteUrlBase is left null.
@param target Data written to this streaam
@param mapping Don't know what this is for, but I can say that....
```

2021-09-15 21:39 UTC, ee-usgs commented on src/main/java/gov/usgs/wma/wqp/transform/BaseMapToJsonTransformer.java
> +	}
Perhaps rename to match its purpose - one of getHostURL() or getContextURL().

2021-09-15 21:39 UTC, ee-usgs commented on src/main/java/gov/usgs/wma/wqp/transform/BaseMapToJsonTransformer.java
>  	public BaseMapToJsonTransformer(OutputStream target, Map<String, String> mapping, ILogService logService, Integer logId, String siteUrlBase) {
Here it would be nice to mention what the `@param siteUrlBase` parameter is expecting.  Is it expecting the full context or just host path?  Trailing slash?

2021-09-24 14:30 UTC, orosz-usgs commented on src/main/java/gov/usgs/wma/wqp/service/ConfigurationService.java
>  	}
I agree that the name of the method is confusing. I was especially confused by the getMyUrlBase() method. But out of scope for this change. Changing the getSiteUrlBase() method would break the convention of having the method name match the name used in application.yml, which could add overhead to understanding the code. Tests might need to be updated, setter method names in other classes changed to match the new name. I propose leaving the refactor for later. Added Java doc.

2021-09-24 14:32 UTC, orosz-usgs commented on src/main/java/gov/usgs/wma/wqp/transform/BaseMapToJsonTransformer.java
> +
Added a Java doc explaining the main point. Left off the parameters for now.

2021-09-24 14:35 UTC, orosz-usgs commented on src/main/java/gov/usgs/wma/wqp/transform/BaseMapToJsonTransformer.java
> +	}
Added Java doc,. See above comment in ConfigurationService

2021-09-24 14:38 UTC, orosz-usgs commented on src/main/java/gov/usgs/wma/wqp/transform/BaseMapToJsonTransformer.java
>  	public BaseMapToJsonTransformer(OutputStream target, Map<String, String> mapping, ILogService logService, Integer logId, String siteUrlBase) {
Added Java doc to getter describing the siteUrlBase property.

2021-09-24 19:10 UTC, duselmann approved these changes
Looks like comments. Merge it.

2021-09-24 19:16 UTC, duselmann approved these changes
looks good, I like the detailed tests. (I did not verify them visually, that is was the test phase is for)

2021-09-24 19:16 UTC, duselmann commented on src/main/java/gov/usgs/wma/wqp/webservice/BaseController.java
> +			transformer = new OrganizationSumMapToJsonTransformer(responseStream, null, logService, logId);
FYI: This method call is omitting the base URL while the following two are updating the method name.

2021-09-24 19:35 UTC, merged